# Generated by Django 4.0.6 on 2022-07-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermetadata',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='user_name',
        ),
    ]
