# Generated by Django 4.1.1 on 2022-10-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
