# Generated by Django 4.2.9 on 2024-01-29 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_artist_about'),
        ('wallet', '0003_wallet_created_at_wallet_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
        ),
    ]
